export enum PRIORITY {
  DEFAULT = 'default',
  NORMAL = 'normal',
  HIGH = 'high',
}

export enum SEX {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum GENDER {
  MAN = 'MAN',
  WOMAN = 'FEMALE',
  NON_BINARY = 'NON_BINARY',
  OTHER = 'OTHER',
}

export enum CIVIL_STATUS {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  SEPARATED = 'SEPARATED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}

export enum SCHOOLING {
  UNEDUCATED = 'UNEDUCATED',
  INCOMPLETE_ELEMENTARY_SCHOOL = 'INCOMPLETE_ELEMENTARY_SCHOOL',
  COMPLETE_HIGHER_EDUCATION = 'COMPLETE_HIGHER_EDUCATION',
  COMPLETE_ELEMENTARY_EDUCATION = 'COMPLETE_ELEMENTARY_EDUCATION',
  INCOMPLETE_HIGHER_EDUCATION = 'INCOMPLETE_HIGHER_EDUCATION',
  COMPLETE_HIGH_SCHOOL = 'COMPLETE_HIGH_SCHOOL',
  INCOMPLETE_HIGH_SCHOOL = 'INCOMPLETE_HIGH_SCHOOL',
}

export enum ETHNICITY {
  WHITE = 'WHITE',
  BLACK = 'BLACK',
  BROWN = 'BROWN',
  INDIGENOUS = 'INDIGENOUS',
  YELLOW = 'YELLOW',
}

export enum SMOKER_STATUS {
  ACTIVE = 'ACTIVE',
  FORMER = 'FORMER',
  INACTIVE = 'INACTIVE',
}

export enum ALCOHOLIC_STATUS {
  ACTIVE = 'ACTIVE',
  FORMER = 'FORMER',
  INACTIVE = 'INACTIVE',
}

export enum EATING_BEHAVIOR {
  HYPERPHAGIC = 'HYPERPHAGIC',
  NIBBLER = 'NIBBLER',
  NIGHT_HUNGER = 'NIGHT_HUNGER',
  EMOTIONAL = 'EMOTIONAL',
  LONG_FASTS = 'LONG_FASTS',
}

export enum ENVIRONMENT {
  CALM = 'CALM',
  ACCOMPANIED = 'ACCOMPANIED',
  AGITATED = 'AGITATED',
  ALONE = 'ALONE',
}

export enum EATING_PLACE {
  HOUSE = 'HOUSE',
  WORK = 'WORK',
  RESTAURANT = 'RESTAURANT',
  OTHER_PEOPLE_HOUSE = 'OTHER_PEOPLE_HOUSE',
}

export enum FAMILIAR_BACKGROUND {
  SAH = 'SAH',
  DM = 'DM',
  OBESITY = 'OBESITY',
  CARDIOPATHIES = 'CARDIOPATHIES',
  CANCER = 'CANCER',
  AMI = 'AMI',
  THYROID_DISEASES = 'THYROID_DISEASES',
  KIDNEY_DISEASES = 'KIDNEY_DISEASES',
  OTHER = 'OTHER',
}

export enum CLINICAL_HISTORY {
  SAH = 'SAH',
  DM = 'DM',
  DYSLIPIDEMIA = 'DYSLIPIDEMIA',
  CVD = 'CVD',
  OBESITY = 'OBESITY',
  CARDIOPATHIES = 'CARDIOPATHIES',
  CANCER = 'CANCER',
  AMI = 'AMI',
  THYROID_DISEASES = 'THYROID_DISEASES',
  KIDNEY_DISEASES = 'KIDNEY_DISEASES',
  GASTRITIS = 'GASTRITIS',
  GERD = 'GERD',
  HEPATIC_STEATOSIS = 'HEPATIC_STEATOSIS',
  OVERWEIGHT = 'OVERWEIGHT',
  OTHER = 'OTHER',
}

export enum SYMPTOM {
  CONSTIPATION = 'CONSTIPATION',
  HEARTBURN = 'HEARTBURN',
  DIARRHEA = 'DIARRHEA',
  FLATULENCE = 'FLATULENCE',
  NAUSEA = 'NAUSEA',
  VOMITING = 'VOMITING',
  CHOKING = 'CHOKING',
  DIFFICULTY_CHEWING = 'DIFFICULTY_CHEWING',
}

export enum WEIGHT_GAIN_REASON {
  CHILDHOOD = 'CHILDHOOD',
  ADOLESCENCE = 'ADOLESCENCE',
  ADULTHOOD = 'ADULTHOOD',
  GENETIC = 'GENETIC',
  EMOTIONAL_DISORDERS = 'EMOTIONAL_DISORDERS',
  MEDICATION_USE = 'MEDICATION_USE',
  HORMONE_DYSFUNCTION = 'HORMONE_DYSFUNCTION',
  HYPERCALORIC_DIET = 'HYPERCALORIC_DIET',
  PREGNANCY = 'PREGNANCY',
}
